const M=[
{id:'r1',ch:0,sk:'Fondamenti',role:'Difesa',d:'Base',t:'c',title:'Proteggi il dato',obj:'Scegli il controllo che tutela la riservatezza dei dati clienti.',brief:'Archivio clienti con dati personali. Devi impedire letture non autorizzate.',o:['Crittografia e controllo accessi','Rinominare il file','Aumentare lo spazio disco','Duplicare il database'],a:0,h:'Pensa a chi può leggere il dato e come proteggerlo se viene copiato.',e:'Crittografia e autorizzazione proteggono la confidenzialità.'},
{id:'r2',ch:0,sk:'Social engineering',role:'Analisi',d:'Base',t:'c',title:'Email sospetta',obj:'Individua il segnale più forte di phishing.',brief:'Da: supporto@micr0soft-help.example\nMessaggio urgente: inserisci password e codice MFA.',o:['Dominio imitato e richiesta urgente di credenziali','Il messaggio ha un oggetto','È presente un saluto','La mail è breve'],a:0,h:'Controlla dominio, urgenza e richiesta di informazioni sensibili.',e:'Dominio imitato, urgenza e richiesta di credenziali sono segnali critici.'},
{id:'r3',ch:0,sk:'Log',role:'Analisi',d:'Base',t:'c',title:'Login anomalo',obj:'Scegli l’evento che richiede priorità.',brief:'08:12 login utente da rete aziendale\n03:41 admin: 18 tentativi falliti da area mai vista\n09:01 backup completato',o:['I tentativi falliti sull’account admin','Il backup completato','Il login aziendale','Nessuno'],a:0,h:'Valuta volume, orario, privilegio e provenienza.',e:'Molti tentativi su un account privilegiato da una zona insolita vanno indagati.'},
{id:'o1',ch:1,sk:'Secure coding',role:'Attacco simulato',d:'Intermedio',t:'c',title:'Trova il punto debole',obj:'Riconosci il rischio nella query del laboratorio.',brief:'string sql = "SELECT * FROM Users WHERE Name = \'" + input + "\'";\nAmbiente locale e simulato.',o:['Input non fidato concatenato nella query','Il nome della variabile','L’uso di una stringa','La mancanza di un commento'],a:0,h:'Osserva come l’input entra nel comando SQL.',e:'La concatenazione rende la struttura della query manipolabile.'},
{id:'o2',ch:1,sk:'Secure coding',role:'Difesa',d:'Intermedio',t:'x',title:'Correggi la query',obj:'Scrivi una soluzione parametrizzata con @name.',brief:'Separa il testo SQL dal valore ricevuto. Non usare concatenazioni.',k:['@name','parameters','add'],sample:'command.CommandText = "SELECT * FROM Users WHERE Name = @name";\ncommand.Parameters.AddWithValue("@name", input);',h:'Usa un parametro e assegna il valore separatamente.',e:'I parametri impediscono che il valore venga interpretato come SQL.'},
{id:'o3',ch:1,sk:'Autorizzazione',role:'Attacco simulato',d:'Intermedio',t:'c',title:'Accesso alla risorsa',obj:'Individua il controllo mancante nella API simulata.',brief:'GET /api/orders/1042\nIl server controlla solo che l’utente sia autenticato.',o:['Verificare proprietà della risorsa o ruolo','Nascondere l’ID nella pagina','Cambiare nome al parametro','Aggiungere un’icona'],a:0,h:'Autenticato non significa autorizzato a ogni ordine.',e:'Serve autorizzazione sulla singola risorsa.'},
{id:'a1',ch:2,sk:'Reti',role:'Attacco simulato',d:'Avanzato',t:'c',title:'Priorità degli asset',obj:'Scegli l’asset più critico nel modello di laboratorio.',brief:'A: sito statico\nB: database clienti\nC: stampante ospiti\nD: monitor sala riunioni',o:['Database clienti','Monitor','Stampante','Sito statico'],a:0,h:'Valuta sensibilità e impatto.',e:'Il database contiene i dati più sensibili e ha impatto maggiore.'},
{id:'a2',ch:2,sk:'Reti',role:'Difesa',d:'Avanzato',t:'c',title:'Ferma il movimento laterale',obj:'Scegli l’architettura che contiene una compromissione.',brief:'Una postazione utente del laboratorio è compromessa. Database e sistemi admin non devono essere raggiungibili direttamente.',o:['Segmentazione e regole minime tra zone','Rete piatta','Condivisioni aperte','Aggiornamenti disabilitati'],a:0,h:'Riduci i percorsi tra aree con funzioni diverse.',e:'La segmentazione limita movimento laterale e impatto.'},
{id:'a3',ch:2,sk:'Hardening',role:'Difesa',d:'Avanzato',t:'x',title:'Minimo privilegio',obj:'Descrivi la policy per un servizio che deve solo leggere /reports.',brief:'Il servizio non necessita scrittura, shell o privilegi amministrativi.',k:['lettura','nega','scrittura'],sample:'Consenti solo lettura su /reports; nega scrittura, shell e privilegi amministrativi.',h:'Concedi solo ciò che serve e nega il resto.',e:'Il minimo privilegio riduce le possibilità di abuso.'},
{id:'e1',ch:3,sk:'Incident response',role:'Difesa',d:'Esperto',t:'c',title:'Primo minuto',obj:'Scegli l’azione iniziale davanti a una postazione sospetta.',brief:'Processi insoliti, connessioni anomale e cifratura rapida di file condivisi in una simulazione.',o:['Isolare la postazione e preservare evidenze','Cancellare i log','Pagare subito','Spegnere tutto senza analisi'],a:0,h:'Contieni senza distruggere le prove.',e:'Isolamento e conservazione delle evidenze limitano il danno e aiutano l’indagine.'},
{id:'e2',ch:3,sk:'Threat modeling',role:'Analisi',d:'Esperto',t:'c',title:'Modella la minaccia',obj:'Scegli la domanda iniziale più utile per un portale clienti.',brief:'Il portale gestirà documenti, pagamenti e ruoli differenti.',o:['Quali asset proteggiamo, da chi e con quale impatto?','Quale colore usare?','Quanti font installare?','Come abbreviare il nome?'],a:0,h:'Parti da asset, attori, confini e conseguenze.',e:'Il threat modeling collega asset, minacce e impatti prima dello sviluppo.'},
{id:'e3',ch:3,sk:'Incident response',role:'Difesa',d:'Esperto',t:'x',title:'Piano di recupero',obj:'Scrivi la sequenza sicura dopo il contenimento.',brief:'Sono disponibili backup verificati e log integri. Evita di reintrodurre la causa.',k:['causa','patch','ripristina','monitora'],sample:'Identifica la causa, applica patch e hardening, ripristina da backup verificato e monitora.',h:'Capisci, correggi, ripristina e osserva.',e:'Ripristinare senza rimuovere la causa può riaprire l’incidente.'},
{id:'x1',ch:4,sk:'Strategia',role:'Red & Blue',d:'Élite',t:'c',title:'Purple team',obj:'Trasforma un test simulato in un miglioramento permanente.',brief:'Il red team esegue una tecnica nel laboratorio, ma il blue team non genera alert.',o:['Condividere evidenze, creare rilevamenti e ripetere il test','Nascondere la tecnica','Cancellare i log','Dichiarare il test superato'],a:0,h:'L’obiettivo è migliorare insieme, non vincere internamente.',e:'Il purple teaming trasforma le simulazioni in controlli verificabili.'},
{id:'x2',ch:4,sk:'Strategia',role:'Difesa',d:'Élite',t:'x',title:'Metrica operativa',obj:'Proponi una metrica per rilevamento e contenimento.',brief:'Il numero di alert non misura la capacità reale del team.',k:['rilevamento','contenimento'],sample:'Misura il tempo medio di rilevamento e il tempo medio di contenimento con simulazioni periodiche.',h:'Misura quanto velocemente scopri e limiti un evento.',e:'Tempi di rilevamento e contenimento misurano la capacità operativa.'},
{id:'x3',ch:4,sk:'Secure SDLC',role:'Difesa',d:'Élite',t:'c',title:'Sicurezza continua',obj:'Scegli il processo che riduce vulnerabilità ricorrenti.',brief:'Ogni release introduce errori simili di autorizzazione e validazione.',o:['Requisiti, review, test automatici e formazione','Correggere solo dopo incidenti','Rimuovere i test','Nascondere gli errori'],a:0,h:'Integra la sicurezza in ogni fase.',e:'Un ciclo di sviluppo sicuro previene e rileva i difetti prima del rilascio.'}
];
const C=[
{name:'1. Recluta',i:'🧭',desc:'Fondamenti, phishing e log.'},
{name:'2. Operatore',i:'🧪',desc:'Secure coding e autorizzazione.'},
{name:'3. Analista',i:'📡',desc:'Reti, segmentazione e hardening.'},
{name:'4. Responder',i:'🚨',desc:'Incident response e threat modeling.'},
{name:'5. Élite',i:'♟️',desc:'Purple team e strategia.'}
];
const R=[{xp:0,n:'Recluta'},{xp:180,n:'Operatore'},{xp:430,n:'Analista'},{xp:760,n:'Responder'},{xp:1100,n:'Difensore élite'}];
const KEY='cyberforge-progress-v1';
let P=load(),S=null,selected=null,answered=false,waiting=null;
const $=id=>document.getElementById(id);
function load(){const f={xp:0,correct:0,total:0,completed:{},attempts:{}};try{return {...f,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return f}}
function save(){localStorage.setItem(KEY,JSON.stringify(P))}
function rank(){return [...R].reverse().find(r=>P.xp>=r.xp)||R[0]}
function unlocked(ch){return ch===0||M.filter(m=>m.ch===ch-1).every(m=>P.completed[m.id])}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'));if(id==='dashboardView')$('navDashboard').classList.add('active');scrollTo(0,0)}
function dashboard(){const done=Object.keys(P.completed).length,pct=Math.round(done/M.length*100);$('rankValue').textContent=rank().n;$('xpValue').textContent=P.xp;$('missionValue').textContent=`${done}/${M.length}`;$('accuracyValue').textContent=P.total?`${Math.round(P.correct/P.total*100)}%`:'0%';$('progressLabel').textContent=`${pct}%`;$('globalProgress').style.width=`${pct}%`;
$('chapters').innerHTML=C.map((c,ch)=>{const list=M.filter(m=>m.ch===ch),n=list.filter(m=>P.completed[m.id]).length,u=unlocked(ch);return `<button class="chapter ${u?'':'locked'}" data-ch="${ch}" ${u?'':'disabled'}><span class="chapter-icon">${c.i}</span><span><strong>${c.name}</strong><small>${c.desc}</small></span><span class="chapter-status">${u?(n===list.length?'Completato':`${n}/${list.length}`):'Bloccato'}</span></button>`}).join('');
document.querySelectorAll('.chapter:not(.locked)').forEach(b=>b.onclick=()=>{const ch=+b.dataset.ch,start=M.find(m=>m.ch===ch&&!P.completed[m.id])||M.find(m=>m.ch===ch);session([start])});
const skills=[...new Set(M.map(m=>m.sk))];$('skills').innerHTML=skills.map(sk=>{const all=M.filter(m=>m.sk===sk),n=all.filter(m=>P.completed[m.id]).length,p=Math.round(n/all.length*100);return `<div class="skill-row"><strong>${sk}</strong><div class="skill-bar"><i style="width:${p}%"></i></div><span>${p}%</span></div>`}).join('')}
function nextPath(){return M.find(m=>unlocked(m.ch)&&!P.completed[m.id])||M[0]}
function session(list){S={list,i:0,xp:0,correct:0};show('missionView');render()}
function quick(){const a=M.filter(m=>unlocked(m.ch)).sort(()=>Math.random()-.5).slice(0,5);session(a)}
function review(){const a=M.filter(m=>(P.attempts[m.id]||0)>0),pool=a.length?a:M.filter(m=>unlocked(m.ch));session(pool.sort((x,y)=>(P.completed[x.id]?1:-1)-(P.completed[y.id]?1:-1)).slice(0,5))}
function render(){answered=false;selected=null;const m=S.list[S.i];$('missionCounter').textContent=`${S.i+1}/${S.list.length}`;$('missionXp').textContent=`+${S.xp} XP`;$('missionProgress').style.width=`${S.i/S.list.length*100}%`;$('missionRole').textContent=m.role;$('missionDifficulty').textContent=m.d;$('missionTitle').textContent=m.title;$('missionObjective').textContent=m.obj;$('missionBriefing').textContent=m.brief;$('feedback').className='feedback hidden';$('verifyButton').classList.remove('hidden');$('nextButton').classList.add('hidden');$('hintButton').disabled=false;
if(m.t==='c'){$('answerArea').innerHTML=`<div class="answer-grid">${m.o.map((o,i)=>`<button class="answer-option" data-i="${i}">${o}</button>`).join('')}</div>`;document.querySelectorAll('.answer-option').forEach(b=>b.onclick=()=>{if(answered)return;selected=+b.dataset.i;document.querySelectorAll('.answer-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')})}else $('answerArea').innerHTML='<textarea id="codeAnswer" class="code-answer" placeholder="Scrivi la tua soluzione o policy..."></textarea>'}
function norm(v){return (v||'').toLowerCase().replace(/\s+/g,' ').trim()}
function verify(){if(answered)return;const m=S.list[S.i];let ok;if(m.t==='c'){if(selected===null)return alert('Seleziona una risposta.');ok=selected===m.a}else{const v=$('codeAnswer').value;if(!v.trim())return alert('Scrivi una risposta.');ok=m.k.every(k=>norm(v).includes(norm(k)))}answered=true;P.total++;P.attempts[m.id]=(P.attempts[m.id]||0)+1;const gain=ok?(m.d==='Base'?40:m.d==='Intermedio'?60:m.d==='Avanzato'?80:100):12;P.xp+=gain;S.xp+=gain;if(ok){P.correct++;S.correct++;P.completed[m.id]=true}save();$('feedback').className=`feedback ${ok?'ok':'bad'}`;$('feedback').innerHTML=`<strong>${ok?'✅ Obiettivo raggiunto':'❌ Analisi da migliorare'}</strong><p>${m.e}</p>${!ok&&m.sample?`<p><strong>Esempio:</strong><br><code>${m.sample}</code></p>`:''}`;$('verifyButton').classList.add('hidden');$('nextButton').classList.remove('hidden');$('missionXp').textContent=`+${S.xp} XP`}
function next(){if(++S.i>=S.list.length){$('missionProgress').style.width='100%';$('resultScore').textContent=`${S.xp} XP`;$('resultTitle').textContent=S.correct===S.list.length?'Operazione perfetta':'Missione completata';$('resultText').textContent=`${S.correct}/${S.list.length} obiettivi raggiunti. Grado attuale: ${rank().n}.`;show('resultView')}else render()}
$('continueButton').onclick=()=>session([nextPath()]);$('dailyButton').onclick=quick;$('navDashboard').onclick=()=>{show('dashboardView');dashboard()};$('navDaily').onclick=quick;$('navReview').onclick=review;$('exitMission').onclick=()=>{show('dashboardView');dashboard()};$('verifyButton').onclick=verify;$('nextButton').onclick=next;$('hintButton').onclick=()=>{const m=S.list[S.i];$('feedback').className='feedback';$('feedback').innerHTML=`<strong>💡 Suggerimento</strong><p>${m.h}</p>`;$('hintButton').disabled=true};$('resultHome').onclick=()=>{show('dashboardView');dashboard()};$('updateButton').onclick=()=>waiting?.postMessage({type:'SKIP_WAITING'});
if('serviceWorker'in navigator)addEventListener('load',async()=>{const r=await navigator.serviceWorker.register('./sw.js');if(r.waiting){waiting=r.waiting;$('updateButton').classList.remove('hidden')}r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',()=>{if(r.installing?.state==='installed'&&navigator.serviceWorker.controller){waiting=r.installing;$('updateButton').classList.remove('hidden')}}));navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());setInterval(()=>r.update(),3600000)});
dashboard();
